Suppress bogus array-bounds warning with GCC 12
Building with GCC 12 is causing many errors like:

sphde/src/sassim.cpp:711:16: error: array subscript 0 is outside array bounds of
'SASBlockHeader [0]' [-Werror=array-bounds]
  711 |   anchorBlock->special = anchorBlock + 1;
      |   ~~~~~~~~~~~~~^~~~~~~

All related to anchorBlock and anchor in src/sassim.cpp:initRegion(). These look
like false-positives because anchorBlock is initialized to a fixed memory
address defined by memLow, and anchor is derived from that as well.

A similar issue with constant addresses has been reported as GCC bug 101379, in
which GCC developers advise to suppress this warning for now.

Tested with GCC 12.0.0 (20210713) and 10.2.1.

Signed-off-by: Matheus Castanho <msc@linux.ibm.com>